export const WondersArr = [
  {
    id: 1,
    name: "Grand Canyon",
desc: "Gorge spectaculaire creusée par le fleuve Colorado pendant des millions d'années. Ses parois multicolores racontent près de deux milliards d'années d'histoire géologique.",
    image: "/images/grand-canyon.jpg",
    location: "Arizona, États-Unis",
    type: "Canyon",
    size: "Environ 446 km de long",
    google_map: "https://www.google.com/maps/search/?api=1&query=Grand+Canyon",
  },
  {
    id: 2,
    name: "Chutes Victoria",
    desc: "Situées sur le fleuve Zambèze, elles forment l'un des plus grands rideaux d'eau du monde. Les habitants les appellent « Mosi-oa-Tunya » : la fumée qui gronde.",
    image: "/images/victoria.jpg",
    location: "Zambie / Zimbabwe",
    type: "Chutes d'eau",
    size: "1,7 km de large, 108 m de haut",
    google_map: "https://www.google.com/maps/search/?api=1&query=Victoria+Falls",
  },
  {
    id: 3,
    name: "Grande Barrière de corail",
    desc: "Plus grand récif corallien de la planète, visible depuis l'espace. Il abrite des milliers d'espèces de poissons, de coraux et de mollusques.",
    image: "/images/barriere-corail.jpg",
    location: "Queensland, Australie",
    type: "Récif corallien",
    size: "Environ 2 300 km de long",
    google_map: "https://www.google.com/maps/search/?api=1&query=Great+Barrier+Reef",
  },
  {
    id: 4,
    name: "Mont Everest",
    desc: "Point culminant de la Terre, situé dans la chaîne de l'Himalaya. Il attire chaque année des alpinistes venus du monde entier.",
    image: "/images/everest.jpg",
    location: "Népal / Chine",
    type: "Montagne",
    size: "8 849 m d'altitude",
    google_map: "https://www.google.com/maps/search/?api=1&query=Mount+Everest",
  },
  {
    id: 5,
    name: "Baie d'Along",
    desc: "Baie parsemée de près de 2 000 îlots calcaires couverts de végétation, qui émergent des eaux émeraude du golfe du Tonkin.",
    image: "/images/halong.jpg",
    location: "Vietnam",
    type: "Baie / relief karstique",
    size: "Environ 1 553 km²",
    google_map: "https://www.google.com/maps/search/?api=1&query=Ha+Long+Bay",
  },
  {
    id: 6,
    name: "Chutes d'Iguazú",
    desc: "Ensemble d'environ 275 cascades situé à la frontière entre l'Argentine et le Brésil, au cœur d'une forêt tropicale protégée.",
    image: "/images/iguazu.jpg",
    location: "Argentine / Brésil",
    type: "Chutes d'eau",
    size: "Environ 2,7 km de large",
    google_map: "https://www.google.com/maps/search/?api=1&query=Iguazu+Falls",
  },
{
    id: 7,
    name: "aurores boréales ",
    desc: "Phénomène lumineux apparut dans le ciel polar, causé par l'interaction des particules solaires avec les molécules de l'atmosphère.",
    image: "/images/aurores-boréales.jpg",
    location: "Pôles Nord et Sud",
    type: "Phénomène atmosphérique",
    size: "Varie selon l'emplacement",
    google_map: "https://www.google.com/maps/search/?api=1&query=Aurora+Borealis",
  },
  
];

